name: Rust

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+" # Triggers on tags like v1.0.0

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build Linux
        run: cargo build --release
      - name: Run tests
        run: cargo test
      - name: Make Artifacts Dir
        run: |
          mkdir build
          cp helpers/c/cfgparser.h build/cfgparser.h
          cp helpers/c/install.sh build/install.sh
          mv target/release/libcfgparser_core.so build/libcfgparser_core.so
      - name: Upload Shared Object
        uses: actions/upload-artifact@v4
        with:
          name: cfgparser-so-${{ github.ref_name }}
          path: |
            build/cfgparser.h
            build/install.sh
            build/libcfgparser_core.so

  build_windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
      - name: Build Windows
        run: cargo build --release --target="x86_64-pc-windows-gnu"
      - name: Run Tests
        run: cargo test --target="x86_64-pc-windows-gnu"
      - name: Upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: cfgparser-dll-${{ github.ref_name }}
          path: target/x86_64-pc-windows-gnu/release/cfgparser_core.dll
